// src/app/projects/[slug]/page.tsx
import React from "react";

import PageHeader from "@/components/PageHeader";
import Container from "@/layout/Container";
import Section from "@/layout/Section";
import TableOfContents from "@/components/TableOfContents";
import FancyHeader from "@/components/FancyHeader";
import ProjectCard from "@/components/ProjectCard";
import CallToAction from "@/components/CallToAction";
import { getContentList, loadContent } from "@/helpers/file-helpers";
import { CONTENT_PATHS } from "@/constants";
import { Metadata } from "next";

type ProjectPostProps = {
  params: {
    slug: string;
  };
};

export const generateStaticParams = async () => {
  const projects = await getContentList(CONTENT_PATHS["projects"]);

  return projects.map((project) => ({
    slug: project.slug,
  }));
};

export const generateMetadata = async ({ params }: any): Promise<Metadata> => {
  const { frontmatter } = await loadContent(
    `${CONTENT_PATHS["projects"]}/${params.slug}`
  );

  return {
    title: frontmatter.title,
    description: frontmatter.summary,
  };
};

const ProjectPost = async ({ params }: ProjectPostProps) => {
  const { frontmatter, content } = await loadContent(
    `${CONTENT_PATHS["projects"]}/${params.slug}`
  );
  const projects = await getContentList(CONTENT_PATHS["projects"]);
  const moreProjects = projects
    .filter((project) => project.draft === false)
    .filter((project) => project.title !== frontmatter.title)
    .sort(() => 0.5 - Math.random())
    .slice(0, 2);
  return (
    <>
      <PageHeader title={frontmatter.title}>
        <p className="lead">{frontmatter.summary}</p>
      </PageHeader>
      <main className="post">
        <Section>
          <img
            src={frontmatter.featuredImage}
            alt={frontmatter.title}
            className="featured-image"
            style={{ marginTop: -8 + "rem" }}
          />
          <Container narrow>
            <div className="content">
              <div className="content__text">{content}</div>
              <div className="content__sidebar">
                <p className="eyebrow">Technology Used</p>
                <ul className="technology">
                  {frontmatter.technology.map((tech: string, index: number) => {
                    return (
                      <li className="technology__item" key={index}>
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          viewBox="0 0 24 24"
                          className="technology__icon-wrapper"
                          fill="currentColor"
                          stroke="none"
                        >
                          <g fill="none">
                            <path d="M0 0h24v24H0Z"></path>
                            <g
                              strokeLinecap="round"
                              strokeWidth="1.5"
                              stroke="currentColor"
                              fill="none"
                              strokeLinejoin="round"
                            >
                              <path d="M4.48 11.98h14.99"></path>
                              <path d="M13.483 5.988L19.513 12l-6.04 6.01"></path>
                            </g>
                          </g>
                        </svg>
                        <span>{tech}</span>
                      </li>
                    );
                  })}
                </ul>
                <p className="eyebrow">Project Links</p>
                <ul>
                  {frontmatter.linkToProject && (
                    <li>
                      <a
                        href={frontmatter.linkToProject}
                        target="_blank"
                        rel="noreferrer noopener"
                      >
                        View Live Project
                      </a>
                    </li>
                  )}
                  {frontmatter.linkToCode && (
                    <li>
                      <a
                        href={frontmatter.linkToCode}
                        target="_blank"
                        rel="noreferrer noopener"
                      >
                        View Code
                      </a>
                    </li>
                  )}
                </ul>
                <TableOfContents />
              </div>
            </div>
          </Container>
        </Section>
        <Section slim>
          <Container narrow>
            <FancyHeader>More Projects</FancyHeader>
            <div className="projects">
              {moreProjects.map((project, index) => {
                return (
                  <ProjectCard
                    key={index}
                    previewImage={project.previewImage}
                    title={project.title}
                    slug={project.slug}
                    summary={project.summary}
                  />
                );
              })}
            </div>
          </Container>
        </Section>
        <Section>
          <Container narrow>
            <CallToAction />
          </Container>
        </Section>
      </main>
    </>
  );
};

export default ProjectPost;

// pages/projects/[slug].vue
<template>
  <header class="header">
    <div class="container container--narrow">
      <h1>{{ project.title }}</h1>
      <p class="lead">
        {{ project.summary }}
      </p>
    </div>
  </header>
  <main id="main" class="post">
    <article class="section pb-7">
      <img
        v-if="project.featuredImage"
        class="featured-image"
        :src="project.featuredImage"
        :alt="project.title"
      />
      <div class="container container--narrow">
        <div class="content">
          <div class="content__image">
            <img
              v-if="!project.featuredImage"
              :src="project.previewImage"
              :alt="project.title"
            />
          </div>
          <div class="content__text">
            <ContentDoc />
          </div>
          <div class="content__sidebar">
            <p class="eyebrow">Technology Used</p>
            <ul class="technology">
              <li
                v-for="tech in project.technology"
                :key="tech"
                class="technology__item"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  class="technology__icon-wrapper"
                  fill="currentColor"
                  stroke="none"
                >
                  <g fill="none">
                    <path d="M0 0h24v24H0Z"></path>
                    <g
                      stroke-linecap="round"
                      stroke-width="1.5"
                      stroke="currentColor"
                      fill="none"
                      stroke-linejoin="round"
                    >
                      <path d="M4.48 11.98h14.99"></path>
                      <path d="M13.483 5.988L19.513 12l-6.04 6.01"></path>
                    </g>
                  </g>
                </svg>
                <span>{{ tech }}</span>
              </li>
            </ul>
            <p class="eyebrow">Project Links</p>
            <ul>
              <li v-if="project.linkToProject">
                <a
                  :href="project.linkToProject"
                  target="_blank"
                  rel="noreferrer noopener"
                  >View Live Project</a
                >
              </li>
              <li v-if="project.linkToCode">
                <a
                  :href="project.linkToCode"
                  target="_blank"
                  rel="noreferrer noopener"
                  >View Code</a
                >
              </li>
            </ul>
            <TableOfContents :headers="tableOfContents" />
          </div>
        </div>
      </div>
    </article>
    <article class="section pb-7">
      <div class="container container--narrow">
        <FancyHeader title="More Projects" />
        <div class="projects">
          <ProjectCard
            v-for="project in moreProjects"
            :key="project.path"
            :project="project"
          />
        </div>
      </div>
    </article>
    <section class="section">
      <div class="container container--narrow">
        <CallToAction />
      </div>
    </section>
  </main>
</template>

<script setup>
import getMetaData from "@/config/getMetaData.js";
import { ref, onMounted } from "vue";
const tableOfContents = ref([]);
const { path } = useRoute();

let queryPath = path;
if (queryPath[queryPath.length - 1] === "/") {
  queryPath = queryPath.replace(/.$/, "");
}

const { data: project } = await useAsyncData(`content-${path}`, () => {
  return queryContent("/projects").where({ _path: queryPath }).findOne();
});

const { data: moreProjects } = await useAsyncData(
  `more-content-${path}`,
  () => {
    return queryContent("/projects")
      .where({ _path: { $ne: path } })
      .find();
  }
);

const getHeaders = () => {
  const headers = Array.from(document.querySelectorAll(".content h2"));
  headers.forEach((header) => {
    const headerObj = {};
    headerObj.text = header.textContent;
    headerObj.link = header.id;
    tableOfContents.value.push(headerObj);
  });
};

onMounted(() => {
  getHeaders();
});

const getMeta = () => {
  const metaData = {
    type: "article",
    url: `https://traekwells.com${path}`,
    title: project.value.title,
    description: project.value.summary,
  };
  return getMetaData(
    metaData,
    {
      property: "article:published_time",
      content: project.value.createdAt,
    },
    {
      property: "article:modified_time",
      content: project.value.updatedAt,
    },
    { name: "twitter:label1", content: "Written by" },
    { name: "twitter:data1", content: "Traek Wells" }
  );
};
useHead({
  meta: getMeta,
  title: project.value.title,
  link: [
    {
      hid: "canonical",
      rel: "canonical",
      href: `https://traekwells.com${path}`,
    },
  ],
});
</script>

<style scoped>
.header {
  padding-bottom: 1rem;
}
</style>
