// src/pages/projects/index.tsx
import React from "react";
import { getAllProjectPostsData } from "@/../lib/posts";
import { ProjectType } from "@/types/types";
import PageHeader from "@/components/PageHeader";
import ProjectCard from "@/components/ProjectCard";
import CallToAction from "@/components/CallToAction";
import Section from "@/layout/Section";
import Container from "@/layout/Container";
import { NextSeo } from "next-seo";

interface ProjectPageProps {
  projects: ProjectType[];
}

export const getStaticProps = () => {
  let projects = getAllProjectPostsData();
  projects = JSON.parse(JSON.stringify(projects));

  return {
    props: {
      projects,
    },
  };
};

const Projects = ({ projects }: ProjectPageProps) => {
  return (
    <>
      <NextSeo
        title="Projects"
        description="Here are some projects that I've worked on that I had a blast doing. I've had the pleasure of working with some great people."
        openGraph={{
          url: "https://www.traekwells.com/projects",
        }}
        canonical="https://www.traekwells.com/projects"
      />
      <PageHeader title="Projects" eyebrow="Work">
        <p className="lead">
          Here are some of my favorite projects that I've worked on.
        </p>
      </PageHeader>
      <main id="main">
        <Section>
          <Container narrow>
            <div className="projects">
              {projects.map((project, index) => {
                return (
                  <ProjectCard
                    key={index}
                    previewImage={project.params.previewImage}
                    title={project.params.title}
                    slug={project.params.slug}
                    summary={project.params.summary}
                  />
                );
              })}
            </div>
          </Container>
        </Section>
        <Section>
          <Container narrow>
            <CallToAction />
          </Container>
        </Section>
      </main>
    </>
  );
};

export default Projects;

// pages/projects/index.vue
<template>
  <PageHeader eyebrow="Work" title="What I've worked on recently">
    <p class="lead">
      Here are some of my favorite projects that I've worked on.
    </p>
  </PageHeader>
  <main id="main">
    <section class="section pb-7">
      <div class="wave-white"></div>
      <div class="container container--narrow">
        <div class="projects">
          <ProjectCard
            v-for="project in projects"
            :key="project.path"
            :project="project"
          />
        </div>
      </div>
    </section>
    <section class="section">
      <div class="container container--narrow">
        <CallToAction />
      </div>
    </section>
  </main>
</template>

<script setup>
import getMetaData from "@/config/getMetaData";
const { data: projects } = await useAsyncData("projects", () => {
  return queryContent("/projects").find();
});
const getMeta = () => {
  const metaData = {
    type: "page",
    url: `https://traekwells.com/projects`,
    title: "Projects",
    description:
      "Stuff I've built through trial and error, a lot of breaks and just hoping that everything worked.",
  };
  return getMetaData(metaData);
};
useHead({
  meta: getMeta,
  title: "Projects",
  link: [
    {
      hid: "canonical",
      rel: "canonical",
      href: `https://traekwells.com/projects`,
    },
  ],
});
</script>
