// components/TableOfContents.vue
<template>
  <p class="eyebrow">Table of Contents</p>
  <ul>
    <li v-for="header of headers" :key="header.id">
      <NuxtLink :to="`#${header.link}`">{{ header.text }}</NuxtLink>
      <!-- <a :href="`#${header.link}`">{{ header.text }}</a> -->
    </li>
  </ul>
</template>

<script setup>
const props = defineProps({
  headers: {
    type: Array,
  },
});
</script>

// src/components/TableOfContents/TableOfContents.tsx
import React from "react";
import Link from "next/link";

interface TableOfContentProps {
  headers: Element[] | undefined;
}

const TableOfContents = ({ headers }: TableOfContentProps) => {
  return (
    <>
      <p className="eyebrow">Table of Contents</p>
      <ul>
        {headers?.map((header, index) => {
          return (
            <li key={index}>
              <Link href={`#${header.id}`}>{header.textContent}</Link>
            </li>
          );
        })}
      </ul>
    </>
  );
};

export default TableOfContents;
