// pages/projects/index.vue
<template>
  <PageHeader eyebrow="Work" title="What I've worked on recently">
    <p class="lead">
      Here are some of my favorite projects that I've worked on.
    </p>
  </PageHeader>
  <main id="main">
    <section class="section pb-7">
      <div class="wave-white"></div>
      <div class="container container--narrow">
        <div class="projects">
          <ProjectCard
            v-for="project in projects"
            :key="project.path"
            :project="project"
          />
        </div>
      </div>
    </section>
    <section class="section">
      <div class="container container--narrow">
        <CallToAction />
      </div>
    </section>
  </main>
</template>

<script setup>
import getMetaData from "@/config/getMetaData";
const { data: projects } = await useAsyncData("projects", () => {
  return queryContent("/projects").find();
});
const getMeta = () => {
  const metaData = {
    type: "page",
    url: `https://traekwells.com/projects`,
    title: "Projects",
    description:
      "Stuff I've built through trial and error, a lot of breaks and just hoping that everything worked.",
  };
  return getMetaData(metaData);
};
useHead({
  meta: getMeta,
  title: "Projects",
  link: [
    {
      hid: "canonical",
      rel: "canonical",
      href: `https://traekwells.com/projects`,
    },
  ],
});
</script>

// src/app/projects/page.tsx
import React from "react";
import PageHeader from "@/components/PageHeader";
import ProjectCard from "@/components/ProjectCard";
import CallToAction from "@/components/CallToAction";
import Section from "@/layout/Section";
import Container from "@/layout/Container";
import { getContentList } from "@/helpers/file-helpers";
import { CONTENT_PATHS } from "@/constants";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Projects",
  description:
    "Here are some projects that I've worked on that I had a blast doing. I've had the pleasure of working with some great people.",
};

const Projects = async () => {
  const projects = await getContentList(CONTENT_PATHS["projects"]);
  return (
    <>
      <PageHeader title="Projects" eyebrow="Work">
        <p className="lead">
          Here are some of my favorite projects that I've worked on.
        </p>
      </PageHeader>
      <main id="main">
        <Section>
          <Container narrow>
            <div className="projects">
              {projects.map((project, index) => {
                return (
                  <ProjectCard
                    key={index}
                    previewImage={project.previewImage}
                    title={project.title}
                    slug={`/projects/${project.slug}`}
                    summary={project.summary}
                  />
                );
              })}
            </div>
          </Container>
        </Section>
        <Section>
          <Container narrow>
            <CallToAction />
          </Container>
        </Section>
      </main>
    </>
  );
};

export default Projects;
