// src/components/CalloutBox/CalloutBox.tsx
import Icon, { IconOptions } from "../Icon";

type CalloutBoxProps = {
  title: string;
  body: string;
  iconType: IconOptions;
};

const CalloutBox = ({ title, body, iconType }: CalloutBoxProps) => {
  return (
    <div className="callout-block">
      <div className="callout-block__icon">
        <Icon type={iconType} />
      </div>
      <div className="callout-block__details">
        <p className="callout-block__title">{title}</p>
        <p>{body}</p>
      </div>
    </div>
  );
};

export default CalloutBox;

// components/CalloutBox.vue
<template>
  <div class="callout-block">
    <div class="callout-block__icon">
      <Icon :type="icon" />
    </div>
    <div class="callout-block__details">
      <p class="callout-block__title">{{ title }}</p>
      <p>
        {{ body }}
      </p>
    </div>
  </div>
</template>

<script setup>
const props = defineProps({
  icon: {
    type: String,
    required: true,
  },
  title: {
    type: String,
    required: true,
  },
  body: {
    type: String,
    required: true,
  },
});
</script>
