// src/components/ProjectCard/ProjectCard.tsx
import Link from "next/link";
import Icon from "../Icon";

interface ProjectCardProps {
  previewImage: string;
  title: string;
  slug: string;
  summary: string;
}

const ProjectCard = ({
  previewImage,
  title,
  slug,
  summary,
}: ProjectCardProps) => {
  return (
    <article className="project">
      <div className="project__image">
        <img src={previewImage} alt={title} />
      </div>
      <div className="project__content">
        <h3>
          <Link href={slug}>{title}</Link>
        </h3>
        <p>{summary}</p>
        <Link href={slug} className="read-more">
          Project Details <Icon type="arrowRight" />
        </Link>
      </div>
    </article>
  );
};

export default ProjectCard;

// components/ProjectCard.vue
<template>
  <article class="project">
    <div class="project__image">
      <img :src="project.previewImage" :alt="project.title" loading="lazy" />
    </div>
    <div class="project__content">
      <h3>
        <NuxtLink :to="project._path">{{ project.title }}</NuxtLink>
      </h3>
      <p>{{ project.summary }}</p>
      <NuxtLink :to="project._path" class="read-more"
        >Project Details <Icon type="arrowRight" />
      </NuxtLink>
    </div>
  </article>
</template>

<script setup>
const props = defineProps({
  project: {
    type: Object,
    required: true,
  },
});
</script>
