// pages/blog/index.vue
<template>
  <PageHeader eyebrow="Writing" title="Some blogs that I’ve written">
    <p class="lead">
      Posts about topics ranging from User Experience, User Interface design,
      HTML, CSS, JavaScript and accessibility. See my
      <NuxtLink to="/journal">journal</NuxtLink> for everything else.
    </p>
  </PageHeader>
  <main>
    <section class="section">
      <div class="wave-white"></div>
      <div class="container container--narrow">
        <div class="blogs">
          <BlogCard v-for="blog in blogs" :key="blog.path" :post="blog" />
        </div>
      </div>
    </section>
  </main>
</template>

<script setup>
import getMetaData from "@/config/getMetaData.js";

const { data: blogs } = await useAsyncData("blogs", () => {
  return queryContent("/blog").where({ draft: false }).find();
});

const getMeta = () => {
  const metaData = {
    type: "page",
    url: `https://traekwells.com/blog`,
    title: "Blog",
    description:
      "Sharing what I've learned in the hopes solidify the knowledge and helping others however I can.",
  };

  return getMetaData(metaData);
};
useHead({
  title: "Blog",
  meta: getMeta,
  link: [
    {
      hid: "canonical",
      rel: "canonical",
      href: `https://traekwells.com/blog`,
    },
  ],
});
</script>

// src/app/blog/page.tsx
import React from "react";
import PageHeader from "@/components/PageHeader";
import BlogCard from "@/components/BlogCard";
import Section from "@/layout/Section";
import Container from "@/layout/Container";
import Link from "next/link";
import { getContentList } from "@/helpers/file-helpers";
import { CONTENT_PATHS } from "@/constants";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog",
  description:
    "A blog where I share what I've learned in the design and front-end development fields.",
};

const Blog = async () => {
  const blogs = await getContentList(CONTENT_PATHS["blog"]);
  return (
    <>
      <PageHeader title="Some blogs that I’ve written">
        <p>
          Posts about topics ranging from User Experience, User Interface
          design, HTML, CSS, JavaScript and accessibility. See my{" "}
          <Link href="/journal">journal</Link> for everything else.
        </p>
      </PageHeader>
      <main id="main">
        <Section>
          <Container narrow>
            <div className="blogs">
              {blogs.map((blog, index) => {
                return (
                  <BlogCard
                    key={index}
                    title={blog.title}
                    slug={`/blog/${blog.slug}`}
                    summary={blog.summary}
                  />
                );
              })}
            </div>
          </Container>
        </Section>
      </main>
    </>
  );
};

export default Blog;
